#!/bin/bash
#SBATCH -p t4v2
#SBATCH --gres=gpu:1
#SBATCH -c 4
#SBATCH --mem=32G
#SBATCH --job-name=protfunc
#SBATCH --output=/checkpoint/arbabi/%j/prot_func.log
#SBATCH --ntasks=1
#SBATCH --time=12:00:00
#SBATCH --qos=normal

cd $SLURM_SUBMIT_DIR
. ~/slurm_scripts/conda.env
export XDG_RUNTIME_DIR=""

python "$@"